// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDd45D6IQ7F6yO0GeSj2PR9DZ9KriRMTc',
    appId: '1:785408111977:android:62b41c8c6ab1c66271f9f8',
    messagingSenderId: '785408111977',
    projectId: 'evently-79',
    storageBucket: 'evently-79.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANZtwH7qJAI-oLfCwUpHQXVaAjO_95mqg',
    appId: '1:785408111977:ios:538d681c348f0a8a71f9f8',
    messagingSenderId: '785408111977',
    projectId: 'evently-79',
    storageBucket: 'evently-79.firebasestorage.app',
    iosBundleId: 'com.evently.evently',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANZtwH7qJAI-oLfCwUpHQXVaAjO_95mqg',
    appId: '1:785408111977:ios:538d681c348f0a8a71f9f8',
    messagingSenderId: '785408111977',
    projectId: 'evently-79',
    storageBucket: 'evently-79.firebasestorage.app',
    iosBundleId: 'com.evently.evently',
  );
}
